export const columnsPending = [
  {
    title: 'INFORMACIÓN SALIDA',
    align: 'center',
    children: [
      {
        title: 'FECHA',
        dataIndex: 'departureDate',
        key: 'departureDate',
        align: 'center',
      },
      {
        title: 'PAQUETE',
        dataIndex: 'templateName',
        key: 'templateName',
        align: 'center',
        isSlot: true,
      },
      {
        title: 'FILE OPE',
        dataIndex: 'opeFile',
        key: 'opeFile',
        align: 'center',
        isSlot: true,
      },
      {
        title: 'FILE(S) COMERCIAL(ES)',
        dataIndex: 'commercialFiles',
        key: 'commercialFiles',
        width: '120px',
        align: 'center',
        isSlot: true,
      },
    ],
  },
  {
    title: 'INFORMACIÓN ENTRADA',
    align: 'center',
    children: [
      {
        title: 'FECHA',
        dataIndex: 'startDate',
        key: 'startDate',
        align: 'center',
      },
      {
        title: 'DESCRIPCIÓN',
        dataIndex: 'name',
        key: 'name',
        align: 'center',
        isSlot: true,
      },
      {
        title: 'CÓDIGO SERVICIO',
        dataIndex: 'serviceCode',
        key: 'serviceCode',
        align: 'center',
        isSlot: true,
        width: '50px',
      },
      {
        title: 'CÓDIGO PROVEEDOR',
        dataIndex: 'providers',
        key: 'providers',
        align: 'center',
        width: '50px',
        isSlot: true,
      },
      {
        title: 'CNT PAX',
        dataIndex: 'paxs',
        key: 'paxs',
        align: 'center',
      },
      {
        title: 'COSTO PAX',
        dataIndex: 'costPax',
        key: 'costPax',
        align: 'center',
      },
      {
        title: 'TOTAL PAX',
        dataIndex: 'totalPax',
        key: 'totalPax',
        align: 'center',
      },
      {
        title: 'CNT POR',
        dataIndex: 'quantityPor',
        key: 'quantityPor',
        align: 'center',
      },
      {
        title: 'COSTO POR',
        dataIndex: 'costPor',
        key: 'costPor',
        align: 'center',
      },
      {
        title: 'TOTAL POR',
        dataIndex: 'totalPor',
        key: 'totalPor',
        align: 'center',
      },
      {
        title: 'TOTAL',
        dataIndex: 'totalAmount',
        key: 'totalAmount',
        align: 'center',
      },
    ],
  },
  {
    title: '',
    dataIndex: 'download',
    key: 'download',
    align: 'center',
    width: '50px',
    isSlot: true,
  },
  {
    title: '',
    dataIndex: 'reserve',
    key: 'reserve',
    align: 'center',
    width: '50px',
    isSlot: true,
  },
];

export const columns = [
  {
    title: 'Nro. Recibo',
    dataIndex: 'receiptNumber',
    key: 'receiptNumber',
    align: 'center',
  },
  {
    title: 'Usuario',
    dataIndex: 'user',
    key: 'user',
    align: 'center',
    isSlot: true,
  },
  {
    title: 'Fec. Recibo',
    dataIndex: 'receiptDate',
    key: 'receiptDate',
    align: 'center',
    width: '50px',
    isSlot: true,
  },
  {
    title: 'Paquete',
    dataIndex: 'templateName',
    key: 'templateName',
    align: 'center',
    isSlot: true,
    width: '150px',
  },
  {
    title: 'Fec. Ini. Paquete',
    dataIndex: 'departureDate',
    key: 'departureDate',
    align: 'center',
    width: '50px',
  },
  {
    title: 'Entrada',
    dataIndex: 'name',
    key: 'name',
    align: 'center',
    isSlot: true,
    width: '150px',
  },
  {
    title: 'Fec. Ini. Servicio',
    dataIndex: 'startDate',
    key: 'startDate',
    align: 'center',
    width: '50px',
  },
  {
    title: 'File OPE Aventura',
    dataIndex: 'opeFile',
    key: 'opeFile',
    align: 'center',
    width: '50px',
  },
  {
    title: 'File(s) Comerciale(s)',
    dataIndex: 'commercialFiles',
    key: 'commercialFiles',
    align: 'center',
    width: '100px',
    isSlot: true,
  },
  {
    title: 'Código Servicio',
    dataIndex: 'serviceCode',
    key: 'serviceCode',
    width: '100px',
    align: 'center',
  },
  {
    title: 'Cód. Proveedor',
    dataIndex: 'providers',
    key: 'providers',
    width: '100px',
    align: 'center',
    isSlot: true,
  },
  {
    title: 'Código Reserva',
    dataIndex: 'ticketCode',
    key: 'ticketCode',
    align: 'center',
    width: '50px',
  },
  {
    title: 'Descripción Reserva',
    dataIndex: 'ticketDescription',
    key: 'ticketDescription',
    align: 'center',
    width: '100px',
  },
  {
    title: 'Anexos',
    dataIndex: 'attachments',
    key: 'attachments',
    align: 'center',
    isSlot: true,
  },
  {
    title: 'CNT. PAX',
    dataIndex: 'paxs',
    key: 'paxs',
    align: 'center',
    width: '50px',
  },
  {
    title: 'Costo PAX',
    dataIndex: 'costPax',
    key: 'costPax',
    align: 'center',
    width: '50px',
  },
  {
    title: 'CNT. POR',
    dataIndex: 'quantityPor',
    key: 'quantityPor',
    align: 'center',
    width: '50px',
  },
  {
    title: 'Costo POR',
    dataIndex: 'costPor',
    key: 'costPor',
    align: 'center',
    width: '50px',
  },
  {
    title: 'Costo Total',
    dataIndex: 'totalAmount',
    key: 'totalAmount',
    align: 'center',
    width: '50px',
  },
  {
    title: '',
    dataIndex: 'send',
    key: 'send',
    align: 'center',
    width: '50px',
    isSlot: true,
  },
];
