// src/api/constants.ts
export const API_BASES = {
  BACKEND_A3: `${import.meta.env.VITE_APP_BACKEND}/api/v1/`,
  BLOCK_CALENDAR_SERVICE: import.meta.env.VITE_APP_BLOCK_CALENDAR_SERVICE,
  OPERATIONAL_GUIDELINES_SERVICE: import.meta.env.VITE_APP_OPERATIONAL_GUIDELINES_SERVICE,
  EVENTS_PUBLISHER_SERVICE: import.meta.env.VITE_APP_EVENTS_PUBLISHER_SERVICE,
  ORDER_CONTROL_SERVICE: import.meta.env.VITE_APP_ORDER_CONTROL_SERVICE,
};
