[supervisord]
nodaemon=true
user=root

[program:high-priority-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/artisan queue:work --queue=high --sleep=3 --tries=3 --max-time=3600 --max-jobs=1000 --timeout=60 --memory=128 --force
autostart=true
autorestart=true
numprocs=2
redirect_stderr=true
user=root
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
redirect_stderr=true

[program:default-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/artisan queue:work --queue=default --sleep=3 --tries=3 --max-time=3600 --max-jobs=1000 --timeout=60 --memory=128 --force
autostart=true
autorestart=true
numprocs=2
redirect_stderr=true
user=root
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
redirect_stderr=true

[program:low-priority-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/artisan queue:work --queue=low --sleep=3 --tries=3 --max-time=3600 --max-jobs=1000 --timeout=60 --memory=128 --force
autostart=true
autorestart=true
numprocs=1
redirect_stderr=true
user=root
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
redirect_stderr=true

[program:app-scheduler]
process_name=%(program_name)s_%(process_num)02d
command=/bin/bash -c "while true; do php /var/www/artisan schedule:run --verbose --no-interaction >> /var/www/storage/logs/scheduler.log 2>&1; sleep 60; done"
autostart=true
autorestart=true
numprocs=1
redirect_stderr=true
user=root
stopwaitsecs=60

[program:update-master-service-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/artisan queue:work --queue=update_master_service --sleep=3 --tries=3 --max-time=3600 --max-jobs=1000 --timeout=60 --memory=128 --force
autostart=true
autorestart=true
numprocs=1
redirect_stderr=true
user=root
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
redirect_stderr=true

[program:stella-worker]
process_name=%(program_name)s_%(process_num)02d
command=php artisan /var/www/artisan/queue:work --queue=stella_sequential --sleep=3 --tries=3 --max-time=3600 --max-jobs=1000 --timeout=60 --memory=128 --force
autostart=true
autorestart=true
numprocs=1  # Solo un worker
redirect_stderr=true
user=root
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
redirect_stderr=true
