// Generated by https://quicktype.io

export interface ServicesZonesResponse {
  success: boolean;
  data: ServiceZone[];
}

export interface ServiceZone {
  id: number;
  city_id: number;
  created_at: string;
  updated_at: string;
  deleted_at: null;
  translations: Translation[];
}

export interface Translation {
  id: number;
  type: string;
  object_id: number;
  slug: string;
  value: string;
  language_id: number;
  created_at: string;
  updated_at: string;
  deleted_at: null;
}
