<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class AddDataTrainUsersTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        $user_emails = [
            "jap@limatours.com.pe",
            "pmf@limatours.com.pe",
            "trenescus2@limatours.pe",
            "ovb@limatours.com.pe",
            "nft@limatours.com.pe",
            "kl@limatours.com.pe",
            "agc@limatours.com.pe",
            "gjm@limatours.com.pe",
            "mcp@limatours.com.pe",
            "mgv@limatours.com.pe",
            "kmv@limatours.com.pe",
            "ssc@limatours.com.pe",
            "pbg@limatours.com.pe",
            "dct@limatours.com.pe",
            "kba@limatours.com.pe",
            "spg@limatours.com.pe",
            "aec@limatours.com.pe",
            "ddl@limatours.com.pe",
            "vcv@limatours.com.pe",
            "rbs@limatours.com.pe",
            "isp@limatours.com.pe",
            "aam.limatours@gmail.com",
            "clo@limatours.com.pe",
            "epl@limatours.com.pe",
            "maa@limatours.com.pe",
            "gtb@limatours.com.pe",
            "kcr@limatours.com.pe",
            "hwr@limatours.com.pe",
            "trenescus1@limatours.com.pe",
            "cac@limatours.com.pe",
            "trenescus2@limatours.com.pe",
            "pmr@limatours.com.pe",
            "lzz@limatours.com.pe",
            "alg@limatours.com.pe",
            "prc@limatours.com.pe",
            "mgr@limatours.com.pe",
            "kbm@limatours.com.pe",
            "atn@limatours.com.pe",
            "apac.limatours@gmail.com",
            "pbm@limatours.com.pe",
            "snb@limatours.com.pe",
            "afc@limatours.com.pe",
            "tvr@limatours.com.pe",
            "amm@limatours.com.pe",
            "gmg@limatours.com.pe",
            "destinationservices@limatours.com.pe",
            "liv@limatours.com.pe",
            "meh@limatours.com.pe",
            "jhe@limatours.com.pe",
            "ema@limatours.com.pe",
            "vgg@limatours.com.pe",
            "mcf@limatours.com.pe",
            "clc@limatours.com.pe",
            "sss@limatours.com.pe",
            "phc@limatours.com.pe",
            "svb@limatours.com.pe",
            "fde@limatours.com.pe",
            "nar@limatours.com.pe",
            "mbb@limatours.com.pe",
            "llc@limatours.com.pe",
            "gsg@limatours.com.pe",
            "fcc@limatours.com.pe",
            "ltr@limatours.com.pe",
            "aoc@limatours.com.pe",
            "dbd@limatours.com.pe",
            "ntn@limatours.com.pe",
            "mco@limatours.com.pe",
            "jka@limatours.com.pe",
            "rlc@limatours.com.pe",
            "kec@limatours.com.pe",
            "rdc@limatours.com.pe",
            "cct@limatours.com.pe",
            "pbo@limatours.com.pe",
            "mer@limatours.com.pe",
            "fte@limatours.com.pe",
            "ovc@limatours.com.pe",
            "nce@limatours.com.pe",
            "erm@limatours.com.pe",
            "ang@limatours.com.pe",
            "asc@limatours.com.pe",
            "brs@limatours.com.pe",
            "eas@limatours.com.pe",
            "mhg@limatours.com.pe",
            "osh@limatours.com.pe",
            "kdl@limatours.com.pe",
            "mrs@limatours.com.pe",
            "rgc@limatours.com.pe",
            "cpa@limatours.com.pe",
            "arn@limatours.com.pe",
            "pss@limatours.com.pe",
            "lms@limatours.com.pe",
            "smc@limatours.com.pe",
            "vhe@limatours.com.pe",
            "wnh@limatours.com.pe",
            "hmc@limatours.com.pe",
            "ymc@limatours.com.pe",
            "per@limatours.com.pe",
            "lom@limatours.com.pe",
            "onc@limatours.com.pe",
            "sya@limatours.com.pe",
            "cmz@limatours.com.pe",
            "gaa@limatours.com.pe",
            "mal@limatours.com.pe",
            "mpg@limatours.com.pe",
            "kbg@limatours.com.pe",
            "fhm@limatours.com.pe",
            "sha@limatours.com.pe",
            "stp@limatours.com.pe",
            "arv@limatours.com.pe",
            "saa@limatours.com.pe",
            "ach@limatours.com.pe",
            "mve@limatours.com.pe",
            "apacp1@limatours.com.pe",
            "mpt@limatours.com.pe"
        ];

        $user_codes = [
            2941,
            2965,
            3533,
            7195,
            7208,
            7209,
            7210,
            7211,
            7212,
            7229,
            7236,
            7239,
            7241,
            7242,
            7243,
            7244,
            7423,
            7498,
            7788,
            8312,
            8530,
            9191,
            9193,
            9407,
            9554,
            9560,
            9804,
            10161,
            10560,
            10994,
            11020,
            11123,
            11429,
            11506,
            2143,
            2706,
            2923,
            2953,
            3355,
            3518,
            3519,
            3520,
            7193,
            7196,
            7197,
            7214,
            7217,
            7222,
            7226,
            7227,
            7232,
            7234,
            7235,
            7240,
            7245,
            7424,
            7480,
            7494,
            7515,
            7582,
            7780,
            7786,
            7950,
            7981,
            8146,
            8147,
            8386,
            8387,
            8388,
            8390,
            8391,
            8503,
            8513,
            8871,
            9005,
            9038,
            9102,
            9103,
            9189,
            9190,
            9192,
            9194,
            9258,
            9372,
            9545,
            9546,
            9547,
            9550,
            9551,
            9552,
            9553,
            9556,
            9557,
            9558,
            9559,
            9765,
            9798,
            9803,
            9986,
            9987,
            9988,
            9989,
            10241,
            10565,
            10567,
            10953,
            10996,
            10997,
            11304,
            11305,
            11686,
            11726,
            11739,
            11815
        ];

        $train_id = \App\Train::where('code', "IR")->first();

        foreach ($user_emails as $i => $user_mail) {
            $user = \App\User::where('email', $user_mail);
            if ($user->count() > 0) {
                $user = $user->first();
                $new_train_user = new \App\TrainUser;
                $new_train_user->train_id = $train_id->id;
                $new_train_user->user_id = $user->id;
                $new_train_user->code = $user_codes[$i];
                $new_train_user->save();
            }
        }
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::disableForeignKeyConstraints();
        \App\TrainUser::truncate();
        Schema::enableForeignKeyConstraints();
    }
}
