export function isAuthenticated(): boolean;
export function isAuthenticatedCognito(): boolean;
export function getUrlAuroraBack(): string | undefined;
export function getUrlAuroraQuoteBack(): string | undefined;
export function getUrlAuroraFront(): string | undefined;
export function getAccessToken(): string | undefined;
export function setCookieLocal(key: string, value: string): void;
export function removeCookiesLocal(): boolean;
export function setAccessToken(value: string): any;
export function getAccessTokenCognito(): string | null;
export function setAccessTokenCognito(value: string): any;
export function setUserCode(value: string): any;
export function getUserCode(): string | undefined;
export function setUserEmail(value: string): any;
export function getUserEmail(): string | undefined;
export function setUserId(value: string): any;
export function getUserId(): string | undefined;
export function setUserType(value: string): any;
export function setUserContract(value: string): void;
export function getUserType(): string | undefined;
export function hasPermission(permission: string, action: string): boolean;
export function setUserName(value: string): any;
export function getUserName(): string | undefined;
export function setUserClientId(value: string): any;
export function setUserRole(value: string): any;
export function getUserClientId(): string | undefined;
export function getUserRole(): string | undefined;
export function isAdmin(): boolean;
export function setUserDepartmentId(value: string): any;
export function getUserDepartmentId(): string | undefined;
export function setUserDepartmentName(value: string): any;
export function getUserDepartmentName(): string | undefined;
export function setUserDepartmentTeamId(value: string): any;
export function getUserDepartmentTeamId(): string | undefined;
export function setUserDepartmentTeamName(value: string): any;
export function getUserDepartmentTeamName(): string | undefined;
export function getUserDisableReservation(): string | undefined;
export function removeCookiesCross(): any;
export function getUserInfo(): {
  username: string | null;
  type: string | null;
  contract: string | null;
};
