import { useDeparturesStore } from '@/stores/adventure';
import { storeToRefs } from 'pinia';

export function useDepartures() {
  const departuresStore = useDeparturesStore();

  const {
    isLoading,
    error,
    getDepartures,
    getCalendarDepartures,
    departure,
    pagination,
    filters,
    file_filters,
    file_types,
    file_options,
    types,
    status,
    paxsByFile,
    guides,
    getCash,
    getCashExtra,
    getServices,
    getTemplateSummary,
    getTemplateServices,
  } = storeToRefs(departuresStore);

  const {
    fetchCalendarAll,
    fetchAll,
    exportAll,
    fetchDeparture,
    save,
    update,
    remove,
    deactivate,
    reset,
    fetchPaxsByFile,
    savePaxsDeparture,
    deletePaxDeparture,
    fetchGuides,
    saveGuideDeparture,
    fetchCashDeparture,
    fetchCashExtraDeparture,
    fetchServices,
    fetchTemplateServices,
    generateCashDeparture,
    closeFileDeparture,
    deleteCloseProcessDeparture,
    hideServiceDeparture,
    closeServiceDeparture,
    updateRealCostDeparture,
    updateTemplateServiceProvidersDeparture,
    resendNotificationCash,
    updateCashStatus,
    getStatus,
    clearFilters,
  } = departuresStore;

  return {
    isLoading,
    error,
    departure,
    pagination,
    filters,
    types,
    status,
    file_filters,
    file_types,
    file_options,
    getStatus,
    templateSummary: getTemplateSummary,
    clearFilters,
    paxsByFile,
    guides,
    departures: getDepartures,
    calendarDepartures: getCalendarDepartures,
    services: getServices,
    templateServices: getTemplateServices,
    cash: getCash,
    cashExtra: getCashExtra,
    fetchCalendarDepartures: fetchCalendarAll,
    fetchDepartures: fetchAll,
    exportDepartures: exportAll,
    findDeparture: fetchDeparture,
    searchPaxsByFile: fetchPaxsByFile,
    searchGuides: fetchGuides,
    fetchDepartureServices: fetchServices,
    fetchDepartureTemplateServices: fetchTemplateServices,
    saveDeparture: save,
    savePaxsToDeparture: savePaxsDeparture,
    saveGuide: saveGuideDeparture,
    deletePaxToDeparture: deletePaxDeparture,
    updateDeparture: update,
    deleteDeparture: remove,
    deactivateDeparture: deactivate,
    resetProgramming: reset,
    searchCash: fetchCashDeparture,
    searchCashExtra: fetchCashExtraDeparture,
    processGenerateCash: generateCashDeparture,
    closeFile: closeFileDeparture,
    deleteCloseProcess: deleteCloseProcessDeparture,
    hideService: hideServiceDeparture,
    closeService: closeServiceDeparture,
    updateRealCost: updateRealCostDeparture,
    updateTemplateServiceProviders: updateTemplateServiceProvidersDeparture,
    resendNotification: resendNotificationCash,
    updateCash: updateCashStatus,
  };
}
